### ISSUE TITLE
Can you tell me if variables are supported?

### ISSUE THREAD

**Issue by Kaerius** [voxpupuli/puppet-augeasproviders_pam#39]
Can you tell me if variables are supported?
$retry, $time

pam { "/etc/pam.d/common-auth":
  ensure    => present,
  service   => common-auth',
  type      => 'auth',
  module    => 'pam_tally.so',
  arguments => ['retry=$retry', 'minlen=$time'],
}

**Comment by tuxmea** [comment]
Hi,

Almost right: Variables need double quotes and curly brackets:

pam { "/etc/pam.d/common-auth":
  ensure => present,
  service => common-auth',
  type => 'auth',
  module => 'pam_tally.so',
  arguments => ["retry=${retry}", "minlen=${time}”],    # <-----
}

Hth,
Martin

**Comment by Kaerius** [comment]
Thank you very much!
